### ISSUE TITLE
Compilation error in a project that reference  merged exe 

### ISSUE THREAD

**Issue by moh-hassan** [MiloszKrajewski/LibZ#28]
I merged exe application with its dll dependencies using the command

		libz.exe inject-dll --assembly $(OutputAssembly)  --include $(OutputPath)\*.dll --move"

when I tried to use the merged exe as a reference for a class library  project which have all types/ interface, vs 2017 fire an exception

>System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OData2Poco.PlugInHelper.LoadPlugin[T](String foldr)
Loader Exception: System.TypeLoadException: Type 'Mylib.MyKey' from assembly 'PluginDemo, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' is attempting to implement an inaccessible interface.
Loader Exception: System.TypeLoadException: Type 'Mylib.MyRequired' from assembly 'PluginDemo, Version=3.0.0.0, Culture=neutr
al, PublicKeyToken=null' is attempting to implement an inaccessible interface.

How to resolve this exception? 
It seems that all types in the merged exe are inaccessible for the compiler.

**Comment by MiloszKrajewski** [comment]
Without getting into details "you cannot". Referencing it further after merging is hard. You would have to make sure that anything you reference is it top/not-injected assembly. I guess it is not the use case ("I tried to use the merged exe as a reference for a class library project which have all types") it was designed for.

**Comment by moh-hassan** [comment]
Thanks for reply.
I think this is applied also for  mergeed dll (not exe). 
No other scenario can fit for purpose of using merged dll as a reference.

**Comment by MiloszKrajewski** [comment]
I did that for (also on github) `lz4net` (it is actually 4 asemblies in one), but I was very careful to expose only things from top assembly. It works as a "proxy" (there is probably a better name for it).

**Comment by moh-hassan** [comment]
It's a good approach. 
I will try to review [lz4net  ](https://github.com/MiloszKrajewski/lz4net) to find out your approach.
Kindly, It's a nice  if you can provide a wiki for how to build a proxy for merged dll assemblies.
The proxy  may be code generation automated tool :) 
Really, your Libz.tool helped me to load external dll plugin at runtime whose dependencies are in the merged console.exe application.
